import requests
import json
import time
from concurrent.futures import ThreadPoolExecutor
from tqdm import tqdm

def fetch_pokemon_data(dex_id):
    try:
        # Fetch Species Data (Gen, Korean Name, Evo Chain)
        species_url = f"https://pokeapi.co/api/v2/pokemon-species/{dex_id}/"
        r = requests.get(species_url)
        if r.status_code != 200:
            return None
        
        data = r.json()
        
        # 1. English Name
        name_en = data['name'].capitalize()
        
        # 2. Korean Name
        name_kr = ""
        for name_entry in data['names']:
            if name_entry['language']['name'] == 'ko':
                name_kr = name_entry['name']
                break
        
        # 3. Generation (e.g. "generation-i")
        generation = data['generation']['name']
        
        # 4. Evolution Chain ID
        evo_chain_url = data['evolution_chain']['url']
        evo_chain_id = int(evo_chain_url.split('/')[-2])
        
        return {
            "id": dex_id,
            "name_en": name_en,
            "name_kr": name_kr,
            "generation": generation,
            "evo_chain_id": evo_chain_id
        }
    except Exception as e:
        # print(f"Error fetching {dex_id}: {e}")
        return None

def build_metadata(limit=900):
    print(f"Fetching metadata for first {limit} Pokemon from PokeAPI...")
    
    metadata = {}
    
    # Use threading for speed (PokeAPI is fast but latency adds up)
    with ThreadPoolExecutor(max_workers=10) as executor:
        results = list(tqdm(executor.map(fetch_pokemon_data, range(1, limit + 1)), total=limit))
        
    for res in results:
        if res:
            metadata[res['id']] = res
            # Also map by English name for easy lookup
            metadata[res['name_en'].lower()] = res
            
    # Save to python file
    with open("pokemon_info.py", "w", encoding='utf-8') as f:
        f.write("# Generated by build_metadata.py\n")
        f.write("POKEMON_DB = " + json.dumps(metadata, indent=4, ensure_ascii=False))
        
    print(f"Saved metadata for {len(results)} entries to pokemon_info.py")

if __name__ == "__main__":
    build_metadata()
